# ----------- CONFIGURABLE START -----------
title:            "A Story of a Knight In A Ruined Fantasy World"
description:      ""
baseurl:     "ASOFK"
url:              "" # Site url, without a slash at the end.
signoff:          "lord-asgord" 
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: G-KZX7FC3LDV
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Chapters
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         YFT Home
    url:          https://yourfantasytranslations.github.io
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"